/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicLayoutRouteImport } from './routes/_public-layout'
import { Route as PrivateLayoutRouteImport } from './routes/_private-layout'
import { Route as PublicLayoutIndexRouteImport } from './routes/_public-layout.index'
import { Route as PublicLayoutCustomerReservationRouteImport } from './routes/_public-layout.customer-reservation'
import { Route as PrivateLayoutUsersRouteImport } from './routes/_private-layout.users'
import { Route as PrivateLayoutTableMapRouteImport } from './routes/_private-layout.table-map'
import { Route as PrivateLayoutReservationsRouteImport } from './routes/_private-layout.reservations'
import { Route as PrivateLayoutInvoicesRouteImport } from './routes/_private-layout.invoices'
import { Route as PrivateLayoutDishesRouteImport } from './routes/_private-layout.dishes'
import { Route as PrivateLayoutCombosRouteImport } from './routes/_private-layout.combos'
import { Route as PrivateLayoutCategoriesRouteImport } from './routes/_private-layout.categories'
import { Route as PrivateLayoutAnalyticsRouteImport } from './routes/_private-layout.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutCustomerReservationRoute =
  PublicLayoutCustomerReservationRouteImport.update({
    id: '/customer-reservation',
    path: '/customer-reservation',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PrivateLayoutUsersRoute = PrivateLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutTableMapRoute = PrivateLayoutTableMapRouteImport.update({
  id: '/table-map',
  path: '/table-map',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutReservationsRoute =
  PrivateLayoutReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutInvoicesRoute = PrivateLayoutInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutDishesRoute = PrivateLayoutDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCombosRoute = PrivateLayoutCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCategoriesRoute = PrivateLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutAnalyticsRoute = PrivateLayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PrivateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLayoutIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof PrivateLayoutAnalyticsRoute
  '/categories': typeof PrivateLayoutCategoriesRoute
  '/combos': typeof PrivateLayoutCombosRoute
  '/dishes': typeof PrivateLayoutDishesRoute
  '/invoices': typeof PrivateLayoutInvoicesRoute
  '/reservations': typeof PrivateLayoutReservationsRoute
  '/table-map': typeof PrivateLayoutTableMapRoute
  '/users': typeof PrivateLayoutUsersRoute
  '/customer-reservation': typeof PublicLayoutCustomerReservationRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLayoutIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof PrivateLayoutAnalyticsRoute
  '/categories': typeof PrivateLayoutCategoriesRoute
  '/combos': typeof PrivateLayoutCombosRoute
  '/dishes': typeof PrivateLayoutDishesRoute
  '/invoices': typeof PrivateLayoutInvoicesRoute
  '/reservations': typeof PrivateLayoutReservationsRoute
  '/table-map': typeof PrivateLayoutTableMapRoute
  '/users': typeof PrivateLayoutUsersRoute
  '/customer-reservation': typeof PublicLayoutCustomerReservationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private-layout': typeof PrivateLayoutRouteWithChildren
  '/_public-layout': typeof PublicLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_private-layout/analytics': typeof PrivateLayoutAnalyticsRoute
  '/_private-layout/categories': typeof PrivateLayoutCategoriesRoute
  '/_private-layout/combos': typeof PrivateLayoutCombosRoute
  '/_private-layout/dishes': typeof PrivateLayoutDishesRoute
  '/_private-layout/invoices': typeof PrivateLayoutInvoicesRoute
  '/_private-layout/reservations': typeof PrivateLayoutReservationsRoute
  '/_private-layout/table-map': typeof PrivateLayoutTableMapRoute
  '/_private-layout/users': typeof PrivateLayoutUsersRoute
  '/_public-layout/customer-reservation': typeof PublicLayoutCustomerReservationRoute
  '/_public-layout/': typeof PublicLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/categories'
    | '/combos'
    | '/dishes'
    | '/invoices'
    | '/reservations'
    | '/table-map'
    | '/users'
    | '/customer-reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/categories'
    | '/combos'
    | '/dishes'
    | '/invoices'
    | '/reservations'
    | '/table-map'
    | '/users'
    | '/customer-reservation'
  id:
    | '__root__'
    | '/_private-layout'
    | '/_public-layout'
    | '/login'
    | '/_private-layout/analytics'
    | '/_private-layout/categories'
    | '/_private-layout/combos'
    | '/_private-layout/dishes'
    | '/_private-layout/invoices'
    | '/_private-layout/reservations'
    | '/_private-layout/table-map'
    | '/_private-layout/users'
    | '/_public-layout/customer-reservation'
    | '/_public-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-layout': {
      id: '/_public-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private-layout': {
      id: '/_private-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-layout/': {
      id: '/_public-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public-layout/customer-reservation': {
      id: '/_public-layout/customer-reservation'
      path: '/customer-reservation'
      fullPath: '/customer-reservation'
      preLoaderRoute: typeof PublicLayoutCustomerReservationRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private-layout/users': {
      id: '/_private-layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateLayoutUsersRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/table-map': {
      id: '/_private-layout/table-map'
      path: '/table-map'
      fullPath: '/table-map'
      preLoaderRoute: typeof PrivateLayoutTableMapRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/reservations': {
      id: '/_private-layout/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof PrivateLayoutReservationsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/invoices': {
      id: '/_private-layout/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof PrivateLayoutInvoicesRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/dishes': {
      id: '/_private-layout/dishes'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof PrivateLayoutDishesRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/combos': {
      id: '/_private-layout/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof PrivateLayoutCombosRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/categories': {
      id: '/_private-layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateLayoutCategoriesRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/analytics': {
      id: '/_private-layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PrivateLayoutAnalyticsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateLayoutAnalyticsRoute: typeof PrivateLayoutAnalyticsRoute
  PrivateLayoutCategoriesRoute: typeof PrivateLayoutCategoriesRoute
  PrivateLayoutCombosRoute: typeof PrivateLayoutCombosRoute
  PrivateLayoutDishesRoute: typeof PrivateLayoutDishesRoute
  PrivateLayoutInvoicesRoute: typeof PrivateLayoutInvoicesRoute
  PrivateLayoutReservationsRoute: typeof PrivateLayoutReservationsRoute
  PrivateLayoutTableMapRoute: typeof PrivateLayoutTableMapRoute
  PrivateLayoutUsersRoute: typeof PrivateLayoutUsersRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateLayoutAnalyticsRoute: PrivateLayoutAnalyticsRoute,
  PrivateLayoutCategoriesRoute: PrivateLayoutCategoriesRoute,
  PrivateLayoutCombosRoute: PrivateLayoutCombosRoute,
  PrivateLayoutDishesRoute: PrivateLayoutDishesRoute,
  PrivateLayoutInvoicesRoute: PrivateLayoutInvoicesRoute,
  PrivateLayoutReservationsRoute: PrivateLayoutReservationsRoute,
  PrivateLayoutTableMapRoute: PrivateLayoutTableMapRoute,
  PrivateLayoutUsersRoute: PrivateLayoutUsersRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutCustomerReservationRoute: typeof PublicLayoutCustomerReservationRoute
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutCustomerReservationRoute: PublicLayoutCustomerReservationRoute,
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
