/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout.users'
import { Route as LayoutReservationsRouteImport } from './routes/_layout.reservations'
import { Route as LayoutInvoicesRouteImport } from './routes/_layout.invoices'
import { Route as LayoutFloorPlanRouteImport } from './routes/_layout.floor-plan'
import { Route as LayoutDishesRouteImport } from './routes/_layout.dishes'
import { Route as LayoutDishCategoriesRouteImport } from './routes/_layout.dish-categories'
import { Route as LayoutCombosRouteImport } from './routes/_layout.combos'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReservationsRoute = LayoutReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesRoute = LayoutInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFloorPlanRoute = LayoutFloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDishesRoute = LayoutDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDishCategoriesRoute = LayoutDishCategoriesRouteImport.update({
  id: '/dish-categories',
  path: '/dish-categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCombosRoute = LayoutCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/combos': typeof LayoutCombosRoute
  '/dish-categories': typeof LayoutDishCategoriesRoute
  '/dishes': typeof LayoutDishesRoute
  '/floor-plan': typeof LayoutFloorPlanRoute
  '/invoices': typeof LayoutInvoicesRoute
  '/reservations': typeof LayoutReservationsRoute
  '/users': typeof LayoutUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/combos': typeof LayoutCombosRoute
  '/dish-categories': typeof LayoutDishCategoriesRoute
  '/dishes': typeof LayoutDishesRoute
  '/floor-plan': typeof LayoutFloorPlanRoute
  '/invoices': typeof LayoutInvoicesRoute
  '/reservations': typeof LayoutReservationsRoute
  '/users': typeof LayoutUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/combos': typeof LayoutCombosRoute
  '/_layout/dish-categories': typeof LayoutDishCategoriesRoute
  '/_layout/dishes': typeof LayoutDishesRoute
  '/_layout/floor-plan': typeof LayoutFloorPlanRoute
  '/_layout/invoices': typeof LayoutInvoicesRoute
  '/_layout/reservations': typeof LayoutReservationsRoute
  '/_layout/users': typeof LayoutUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/analytics'
    | '/combos'
    | '/dish-categories'
    | '/dishes'
    | '/floor-plan'
    | '/invoices'
    | '/reservations'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/analytics'
    | '/combos'
    | '/dish-categories'
    | '/dishes'
    | '/floor-plan'
    | '/invoices'
    | '/reservations'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about'
    | '/login'
    | '/_layout/analytics'
    | '/_layout/combos'
    | '/_layout/dish-categories'
    | '/_layout/dishes'
    | '/_layout/floor-plan'
    | '/_layout/invoices'
    | '/_layout/reservations'
    | '/_layout/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reservations': {
      id: '/_layout/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof LayoutReservationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices': {
      id: '/_layout/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof LayoutInvoicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/floor-plan': {
      id: '/_layout/floor-plan'
      path: '/floor-plan'
      fullPath: '/floor-plan'
      preLoaderRoute: typeof LayoutFloorPlanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dishes': {
      id: '/_layout/dishes'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof LayoutDishesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dish-categories': {
      id: '/_layout/dish-categories'
      path: '/dish-categories'
      fullPath: '/dish-categories'
      preLoaderRoute: typeof LayoutDishCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/combos': {
      id: '/_layout/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof LayoutCombosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutCombosRoute: typeof LayoutCombosRoute
  LayoutDishCategoriesRoute: typeof LayoutDishCategoriesRoute
  LayoutDishesRoute: typeof LayoutDishesRoute
  LayoutFloorPlanRoute: typeof LayoutFloorPlanRoute
  LayoutInvoicesRoute: typeof LayoutInvoicesRoute
  LayoutReservationsRoute: typeof LayoutReservationsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutCombosRoute: LayoutCombosRoute,
  LayoutDishCategoriesRoute: LayoutDishCategoriesRoute,
  LayoutDishesRoute: LayoutDishesRoute,
  LayoutFloorPlanRoute: LayoutFloorPlanRoute,
  LayoutInvoicesRoute: LayoutInvoicesRoute,
  LayoutReservationsRoute: LayoutReservationsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
